spring:
  datasource:
    url: jdbc:postgresql://tcp-mo5.mogenius.io:55448/covid-db
    username: test-user
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

